language: c

notifications:
  email: false

git:
  depth: 3

os: 
    - linux
    - osx


script: 
    - cc -o tonegen tonegen.c -lm
    - ./tonegen -d - -t 0.1 -r 44100 > test.raw
    - ls -l test.raw
    - test $(du test.raw -b | cut -f 1) -eq 17644
